name: Compile geoip-cli
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
        with:
          ref: cli

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Cross compile
        run: |
          mkdir bin
          GOOS=linux GOARCH=amd64 GOAMD64=v3 go build -o ./bin/geoip-linux-amd64-v3
          GOOS=windows GOARCH=amd64 GOAMD64=v3 go build -o ./bin/geoip-windows-amd64-v3.exe

      - name: Get geoip-cli version
        run: |
          CLI_VERSION=$(curl -f --retry 3 --retry-delay 4 'https://api.github.com/repos/letsky192/geoip/branches/cli' \
            | jq -r '.commit.commit.author.date' | cut -d'T' -f1 | tr -d '-')
          echo "cli_version=$CLI_VERSION" >> $GITHUB_ENV

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          name: geoip-cli ${{ env.cli_version }}
          tag_name: ${{ env.cli_version }}
          target_commitish: cli
          generate_release_notes: false
