name: Compile geoip-cli
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
        with:
          ref: cli

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Cross compile
        run: |
          mkdir bin
          GOOS=linux GOARCH=amd64 GOAMD64=v3 go build -o './bin/geoip-linux-amd64-v3'
          GOOS=windows GOARCH=amd64 GOAMD64=v3 go build -o './bin/geoip-windows-amd64-v3.exe'

      - name: Get geoip-cli version
        run: |
          BIN_VERSION=$(curl -f --retry 3 --retry-delay 4 \
                            --url 'https://api.github.com/repos/letsky192/geoip/branches/cli' \
                            -H 'Authorization: token ${{ github.token }}' \
                        | jq -r '.commit.commit.author.date' | cut -d 'T' -f 1 | tr -d '-')
          echo "bin_version=$BIN_VERSION" >> $GITHUB_ENV

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*
          commit: cli
          name: geoip-cli ${{ env.bin_version }}
          tag: ${{ env.bin_version }}
