name: Build geoip files
on:
  workflow_dispatch:
  schedule:
    - cron: "24 0-15 * * *"

jobs:
  compare:
    runs-on: ubuntu-latest

    outputs:
      local_tag: ${{ steps.get_local_tag.outputs.tag }}
      upstream_tag: ${{ steps.get_upstream_tag.outputs.tag }}

    steps:
      - name: Get Local Tag
        id: get_local_tag
        run: |
          LOCAL_LATEST_TAG=$(curl -s https://api.github.com/repos/letsky192/geoip/releases/latest | jq -r '.tag_name')
          echo "tag=$LOCAL_LATEST_TAG" >> "$GITHUB_OUTPUT"

      - name: Get Upstream Tag
        id: get_upstream_tag
        run: |
          UPSTREAM_LATEST_TAG=$(curl -s https://api.github.com/repos/Loyalsoldier/geoip/releases/latest | jq -r '.tag_name')
          echo "tag=$UPSTREAM_LATEST_TAG" >> "$GITHUB_OUTPUT"


  build:
    runs-on: ubuntu-latest
    needs: compare
    if: ${{ needs.compare.outputs.local_tag != needs.compare.outputs.upstream_tag }}

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Build geoip files
        run: |
          go run ./

      - name: Verify mmdb files
        run: |
          cd ./output/maxmind || exit 1
          go install -v github.com/maxmind/mmdbverify@latest
          for name in $(ls *.mmdb); do
            $(go env GOPATH)/bin/mmdbverify -file ${name}
          done

      - name: Generate sha256 checksum for dat files
        run: |
          cd ./output/dat || exit 1
          for name in $(ls *.dat); do
            sha256sum ${name} > ./${name}.sha256sum
          done

      - name: Generate sha256 checksum for mmdb files
        run: |
          cd ./output/maxmind || exit 1
          for name in $(ls *.mmdb); do
            sha256sum ${name} > ./${name}.sha256sum
          done

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          mv ./output/dat/*.dat ./output/dat/*.sha256sum ./output/maxmind/*.mmdb ./output/maxmind/*.sha256sum ./publish/
          cp -fpPR ./output/text ./publish

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add -A
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u geoip release

      - name: Remove some files to avoid publishing to GitHub release
        run: rm -rf ./publish/text

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./publish/*
          tag: ${{ needs.compare.outputs.upstream_tag }}
