name: Build ip set
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get install -y bgpdump html2text
          cargo install bgptools

      - name: Set variables
        run: |
          echo "PATH=$(go env GOPATH)/bin:${PATH}" >> $GITHUB_ENV
          echo "IP6UPSTREAM=http://archive.routeviews.org/route-views6/bgpdata" >> $GITHUB_ENV
          echo "MONTH6=$(date -u +%Y.%m)" >> $GITHUB_ENV

      - name: Generate AS table
        run: curl -sSL https://bgp.potaroo.net/cidr/autnums.html | awk '-F[<>]' '{print $3,$5}' | grep '^AS' > asnames.txt

      - name: Fetch bgp data
        run: |
          curl -f --retry 3 --retry-delay 4 -o rib.bz2 "http://archive.routeviews.org/dnszones/rib.bz2"
          LATEST6=$(curl -sL ${{ env.IP6UPSTREAM }}/${{ env.MONTH6 }}/RIBS|html2text|grep bz2|awk '{print $3}'|tail -n 1)
          TAG_NAME=$(echo ${LATEST6}|awk '{gsub("(rib.|.bz2)",""); print $1}')
          curl -f --retry 3 --retry-delay 4 -o rib6.bz2 "$IP6UPSTREAM/$MONTH6/RIBS/$LATEST6"
          echo "RELEASE_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Dump v4 bgp date
        run: |
          echo "running bgpdump ..."
          bgpdump -m -O rib.txt rib.bz2
          echo "finish bgpdump"

      - name: Dump v6 bgp date
        run: |
          echo "running bgpdump ..."
          bgpdump -m -O rib6.txt rib6.bz2
          echo "finish bgpdump"

      - name: Generate China IPv4 list
        run: |
          cat asnames.txt | grep -P "CN\$" | grep -vPi "AS45102" | awk '{gsub(/AS/, ""); print $1}' > cnasn.list
          cat cnasn.list | xargs bgptools -b rib.txt > cn.txt
          cat cnasn.list | xargs bgptools -b rib6.txt > cn6.txt
          mkdir bin
          mv cn.txt ./bin/cn.txt
          mv cn6.txt ./bin/cn6.txt

    #  - name: Get geoip-cli version
    #    run: |
    #      COMMIT_DATE=$(curl -f --retry 3 --retry-delay 4 'https://api.github.com/repos/letsky192/geoip/branches/cli' \
    #        | jq -r '.commit.commit.author.date' | cut -d'T' -f1 | tr -d '-')
    #      echo "commit_date=$COMMIT_DATE" >> $GITHUB_ENV

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          name: '调试123'
          tag_name: 111
          generate_release_notes: false
