name: Test bunzip
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bgpdump html2text

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: bgptools@0.1.1

      - name: Get geoip-cli
        run: |
          curl -f --retry 3 --retry-delay 4 -o geoip -L 'https://github.com/letsky192/geoip/releases/latest/download/geoip-linux-amd64-v3'
          chmod u+x ./geoip

      - name: Set variables
        run: |
          echo "IP4UPSTREAM=http://archive.routeviews.org/route-views2/bgpdata" >> $GITHUB_ENV
          echo "IP6UPSTREAM=http://archive.routeviews.org/route-views6/bgpdata" >> $GITHUB_ENV
          echo "MONTH6=$(date -u +%Y.%m)" >> $GITHUB_ENV
          echo "release_name=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Generate AS table
        run: curl -sSL https://bgp.potaroo.net/cidr/autnums.html | awk '-F[<>]' '{print $3,$5}' | grep '^AS' > asnames.txt

      - name: Fetch bgp data
        run: |
          LATEST4=$(curl -sL ${{ env.IP4UPSTREAM }}/${{ env.MONTH6 }}/RIBS|html2text|grep bz2|awk '{print $3}'|tail -n 1)
          curl -f --retry 3 --retry-delay 4 -o rib.bz2 "$IP4UPSTREAM/$MONTH6/RIBS/$LATEST4"
          LATEST6=$(curl -sL ${{ env.IP6UPSTREAM }}/${{ env.MONTH6 }}/RIBS|html2text|grep bz2|awk '{print $3}'|tail -n 1)
          curl -f --retry 3 --retry-delay 4 -o rib6.bz2 "$IP6UPSTREAM/$MONTH6/RIBS/$LATEST6"
          bzip2 -dk rib.bz2
          bzip2 -dk rib6.bz2

      - name: Dump v4 bgp date
        if: ${{ false }}
        run: |
          echo "running bgpdump ..."
          bgpdump -m -O rib.txt rib.bz2
          echo "finish bgpdump"

      - name: Dump v6 bgp date
        if: ${{ false }}
        run: |
          echo "running bgpdump ..."
          bgpdump -m -O rib6.txt rib6.bz2
          echo "finish bgpdump"

      - name: Generate China IP list
        run: |
          cat asnames.txt | grep -P "CN\$" | grep -vPi "AS45102" | awk '{gsub(/AS/, ""); print $1}' > cnasn.list
          cat cnasn.list | xargs bgptools -m ./rib | ./geoip merge > cn4.txt
          cat cnasn.list | xargs bgptools -m ./rib6 | ./geoip merge > cn6.txt
          ls

      - name: Git push assets to "release5" branch
        run: |
          mkdir publish
          mv ./cn4.txt ./publish/cn4.txt
          mv ./cn6.txt ./publish/cn6.txt
          mv ./cnasn.list ./publish/cnasn.list
          cd publish
          git init -b release5
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m '${{ env.release_name }}'
          git remote add origin 'https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git'
          git push -f -u origin release5
